// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleAddAccount(arg1) {
  return window['go']['main']['App']['HandleAddAccount'](arg1);
}

export function HandleCheck() {
  return window['go']['main']['App']['HandleCheck']();
}

export function HandleDeleteAccount(arg1) {
  return window['go']['main']['App']['HandleDeleteAccount'](arg1);
}

export function HandleReadAccount() {
  return window['go']['main']['App']['HandleReadAccount']();
}
