// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';

export function HandleAddAccount(arg1:account.Account):Promise<void>;

export function HandleDeleteAccount(arg1:string):Promise<void>;

export function HandleReadAccount():Promise<Array<account.Account>>;
